services:
  app:
    build: .
    volumes:
      - .:/var/www
      - ./database:/var/www/src/database
      - ./.env:/var/www/.env
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/src/database/database.sqlite
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "php", "artisan", "queue:work", "--once"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
